CREATE DATABASE AssinaturaJogos;
USE AssinaturaJogos;


CREATE TABLE IF NOT EXISTS generos (
    id_genero INT AUTO_INCREMENT PRIMARY KEY,
    nome_genero VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS plataformas (
    id_plataforma INT AUTO_INCREMENT PRIMARY KEY,
    nome_plataforma VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario (
    id_user INT AUTO_INCREMENT,
    nome_user VARCHAR(50) NOT NULL,
    login_user VARCHAR(50) NOT NULL,
    senha_user VARCHAR(50) NOT NULL,
    email_user VARCHAR(50) NOT NULL UNIQUE,
    saldo decimal(10,2) default 1000.00,
    PRIMARY KEY(id_user)
);

CREATE TABLE IF NOT EXISTS jogos (
    id_jogo INT AUTO_INCREMENT,
    video_jogo VARCHAR(255),
    preco_jogo DECIMAL(10,2) NOT NULL,
    nome_jogo VARCHAR(100) NOT NULL UNIQUE,
    criador_jogo VARCHAR(100) NOT NULL,
    descricao_jogo VARCHAR(2000) NOT NULL,
    data_lancamento DATE,
    genero VARCHAR(50),
    plataforma VARCHAR(50),
	nota_jogo Decimal(10,1) NOT NULL,
    id_genero INT NOT NULL,
    id_plataforma INT NOT NULL,
    PRIMARY KEY(id_jogo),
    FOREIGN KEY (id_genero) REFERENCES generos(id_genero),
    FOREIGN KEY (id_plataforma) REFERENCES plataformas(id_plataforma)
);

CREATE TABLE IF NOT EXISTS itens_do_pedido (
    item_id INT AUTO_INCREMENT,
    pedido_id INT NOT NULL,
    id_jogo INT NOT NULL,
    id_plataforma INT NOT NULL,
    preco_na_venda DECIMAL(10,2),
    chave_de_ativacao VARCHAR(100),
    PRIMARY KEY(item_id),
    FOREIGN KEY(id_jogo) REFERENCES jogos(id_jogo),
    FOREIGN KEY(id_plataforma) REFERENCES plataformas(id_plataforma)
);

create table if not exists carrinho(
id_carrinho INT PRIMARY KEY AUTO_INCREMENT,
id_jogo INT,
id_user INT,
FOREIGN KEY(id_jogo) REFERENCES jogos(id_jogo),
FOREIGN KEY(id_user) REFERENCES usuario(id_user)
);

INSERT INTO generos (nome_genero) VALUES
/*ID 1*/('Ação'),
/*ID 2*/('Aventura'),
/*ID 3*/('Luta'),
/*ID 4*/('RPG'),
/*ID 5*/('Terror'),
/*ID 6*/('Corrida'),
/*ID 7*/('Estrategia'),
/*ID 8*/('Sobrevivência'),
/*ID 9*/('Cartas'),
/*ID 10*/('Simulação');
INSERT INTO plataformas (nome_plataforma) VALUES
/*ID 1*/('PC'),
/*ID 2*/('PS4'),
/*ID 3*/('PS5'),
/*ID 4*/('Xbox One'),
/*ID 5*/('Xbox Series S');


INSERT INTO jogos (video_jogo, preco_jogo, nome_jogo, criador_jogo, descricao_jogo, data_lancamento, genero, plataforma, nota_jogo, id_genero, id_plataforma)
VALUES
/*PC*/
  ('uCaWqXP54Mc',49.99,'Uma_Musume_Pretty_Derby','Cygames',				 'Uma Musume Pretty Derby é um jogo que mistura corrida, treinamento e elementos de RPG. O jogador assume o papel de treinador de garotas inspiradas em cavalos de corrida lendários da vida real, ajudando-as a desenvolver atributos, aprender habilidades e vencer competições cada vez mais difíceis. Além das corridas, o jogo apresenta histórias individuais para cada personagem, eventos especiais e apresentações musicais após as vitórias, criando uma experiência única para fãs de esportes, anime e gerenciamento.',   								    '2021-02-24','Corrida'   ,'PC',  8.5 ,6 ,1),
  ('7JFOLJv4s6Y',59.90,'Far_Cry_4',				 'Ubisoft',				 'Far Cry 4 é um jogo de ação e aventura em mundo aberto ambientado em Kyrat, uma região fictícia inspirada nos Himalaias. O jogador assume o papel de Ajay Ghale, que retorna à sua terra natal para cumprir o último desejo de sua mãe, mas acaba envolvido em uma guerra civil contra o tirânico rei Pagan Min. Com uma grande variedade de armas, veículos e atividades secundárias, o jogo oferece liberdade para explorar montanhas, florestas e fortalezas inimigas, permitindo diferentes estilos de combate, desde confrontos diretos até abordagens furtivas.',	'2014-11-18','Ação'      ,'PC',  8.7 ,1 ,1),	
  ('DfJaUpW_P00',39.90,'Lego_Batman',			 'Traveller Tales',		 'LEGO Batman: Legacy reúne o universo do Cavaleiro das Trevas em uma divertida aventura construída com peças LEGO. Os jogadores podem controlar Batman, Robin e diversos heróis e vilões da DC Comics enquanto enfrentam desafios, resolvem quebra-cabeças e participam de combates cheios de humor característicos da franquia LEGO. Com dezenas de personagens desbloqueáveis, fases inspiradas em momentos marcantes dos quadrinhos e animações divertidas, o jogo oferece entretenimento para jogadores de todas as idades.',    									'2008-09-23','Aventura'  ,'PC',  8.4 ,2 ,1),
  ('w8vPZrMFiZ4',59.99,'Honkai_Star_Rail',		 'HoYoverse',			 'Honkai: Star Rail é um RPG de turnos desenvolvido pela HoYoverse que leva os jogadores a uma aventura interplanetária a bordo do Expresso Astral. Durante a jornada, é possível conhecer diversos personagens com habilidades únicas, explorar diferentes mundos e enfrentar inimigos poderosos utilizando estratégias em combate. Com gráficos de alta qualidade, narrativa envolvente e atualizações frequentes, o jogo combina exploração, coleção de personagens e batalhas táticas em um universo de ficção científica.',												'2023-04-26','RPG'       ,'PC',  9.0 ,4 ,1),
  ('jkzRbc2VlXY',47.99,'Epic_Battle_Fantasy_5',	 'Kupo Games',           'Epic Battle Fantasy 5 é um RPG por turnos indie que mistura combate estratégico com humor e referências a videogames clássicos (principalmente Final Fantasy e outros JRPGs). O jogo acompanha um grupo de personagens excêntricos (Matt, Natalie, Lance, Anna e NoLegs) em uma aventura cheia de batalhas, exploração e situações absurdas. O enredo começa com uma investigação sobre meteoros misteriosos e rapidamente evolui para eventos maiores envolvendo monólitos, criaturas corrompidas e ameaças cósmicas.',                      '2018-11-30','Aventura'  ,'PC',  9.0 ,2 ,1),
  ('CHAbHz8iYHc',18.70,'Plants_VS_Zombies',      'PopCap Games',         'Um jogo de ação-estratégia totalmente novo da PopCap, desenvolvedora de Bejeweled e Peggle! Zumbis estão invadindo seu lar e sua única defesa é seu arsenal de plantas! Armado com um viveiro de plantas exterminadoras de zumbis como atiradores de ervilha e bombas de cereja, você precisará pensar rápido e plantar mais rápido'                                                                                                                                                                                           ,                      '2009-05-05','Estrategia','PC', 9.5,7,1),                                                                       
  ('kWnzRGD9NDE', 19.99, 'Half-Life_2',          'Valve',                'Half-Life 2 é um dos jogos mais influentes da história dos videogames, trazendo uma experiência revolucionária de física aplicada, narrativa imersiva e gameplay em primeira pessoa extremamente fluido. O jogador controla Gordon Freeman em um mundo distópico dominado pela Combine, enfrentando soldados, criaturas alienígenas e resolvendo puzzles ambientais com a famosa Gravity Gun. O jogo se destaca pela ambientação, história cinematográfica e design de fases extremamente avançado para sua época.', '2004-11-16', 'Ação', 'PC', 9.8, 1, 1),
  ('JGhIXLO3ul8', 19.99, 'Dead_By_Daylight',     'Behaviour Interactive','Dead by Daylight é um jogo multiplayer assimétrico de terror onde quatro sobreviventes precisam escapar de um assassino enquanto trabalham juntos para consertar geradores e fugir do mapa. Cada partida é única devido aos diferentes killers, perks e mapas, criando uma experiência intensa e imprevisível. O jogo se destaca pela atmosfera sombria, colaboração entre jogadores e a tensão constante de perseguição.', '2016-06-14', 'Terror', 'PC', 8.5, 5, 1),
  ('7DbBwNpOkEI', 0.00, 'Yu-Gi-Oh!_Master_Duel', 'Konami',               'Yu-Gi-Oh! Master Duel é a versão digital oficial do famoso jogo de cartas colecionáveis, trazendo regras completas do TCG com milhares de cartas disponíveis. O jogo possui gráficos animados durante as invocações, sistema competitivo online ranqueado e eventos sazonais. É uma experiência estratégica profunda onde montagem de deck, leitura do oponente e timing são essenciais para vencer duelos.', '2022-01-19', 'Cartas', 'PC', 9.0, 9, 1),
  ('HLUY1nICQRY', 0.00, 'Genshin_Impact',        'HoYoverse',            'Genshin Impact é um RPG de mundo aberto com foco em exploração livre, combate elemental e narrativa expansiva. O jogador assume o papel do Viajante, que percorre o mundo de Teyvat em busca de seu irmão perdido, encontrando diversas nações inspiradas em culturas diferentes, cada uma com sua própria história, política e conflitos. O jogo se destaca pelo sistema de elementos que interagem entre si, permitindo combos estratégicos no combate, além de um vasto elenco de personagens jogáveis com habilidades únicas e um mundo vivo repleto de segredos, chefes e eventos constantes.', '2020-09-28', 'RPG', 'PC', 9.2, 4, 1),
  ('aeu87fKjV5w', 0.00, 'Zenless_Zone_Zero',     'HoYoverse',            'Zenless Zone Zero é um RPG de ação ambientado em um mundo futurista pós-apocalíptico onde a humanidade sobrevive após a destruição causada por fenômenos chamados Hollows. O jogador atua como um Proxy, guiando equipes de personagens em combates rápidos, estilizados e altamente dinâmicos dentro dessas dimensões perigosas. O jogo combina exploração urbana com missões de combate em tempo real, sistema de esquiva e combos rápidos, além de forte identidade visual inspirada em estética cyberpunk e animações fluidas.', '2024-07-04', 'Ação', 'PC', 8.8, 1, 1),
/*PS4*/
 ('BY9-jWQQHgw',191.59,'Five_Nights_at_Freddys_Security_Breach', 'Steel Wool Studios',	'Five Nights at Freddys: Security Breach é um jogo de terror e sobrevivência ambientado em um enorme centro de entretenimento chamado Mega Pizzaplex. O jogador controla Gregory, uma criança presa dentro do local durante a noite, que precisa escapar dos animatrônicos enquanto desvenda os mistérios do estabelecimento. Diferente dos jogos anteriores da série, Security Breach oferece exploração livre em um ambiente tridimensional, perseguições intensas e diversas áreas para investigar.',																	'2021-12-16','Terror'    ,'PS4', 6.0 ,5 ,2),
 ('CRLglREYEDs',39.99,'Shadow_of_Mordor',						'Monolith Productions',	'Middle-earth: Shadow of Mordor é um jogo de ação e aventura ambientado no universo de O Senhor dos Anéis. O jogador controla Talion, um guardião que retorna da morte em busca de vingança contra as forças de Sauron. O grande destaque do jogo é o Sistema Nêmesis, que permite que inimigos sobrevivam aos confrontos, evoluam em poder e desenvolvam rivalidades únicas com o jogador. Com combate dinâmico, exploração em mundo aberto e elementos de furtividade, o jogo oferece uma experiência marcante para fãs da Terra-média.',									'2014-09-30','Ação'      ,'PS4', 8.5 ,1 ,2),
 ('JnUbg-9v_bE', 39.99, 'Dragon_Ball_Xenoverse_2',               'Bandai Namco',           'Dragon Ball Xenoverse 2 é um RPG de ação baseado no universo de Dragon Ball, onde o jogador cria seu próprio personagem e participa de batalhas icônicas da série, alterando eventos da história original. O jogo possui combates em arena 3D, customização profunda de personagens, habilidades especiais e exploração de cidades como Conton City. Ele também conta com modo online, missões cooperativas e diversos DLCs com personagens adicionais.', '2016-10-25', 'Luta', 'PS4', 8.7, 3, 2),
 ('FyIwEFXOcaE', 50.00, 'God of War', 'Santa Monica Studio', 'God of War reinventa a franquia ao transportar Kratos para o mundo da mitologia nórdica. Agora acompanhado por seu filho Atreus, ele embarca em uma jornada para cumprir o último desejo de sua esposa. O jogo apresenta um sistema de combate mais estratégico e brutal, exploração semiaberta, evolução de equipamentos e uma narrativa emocionante centrada na relação entre pai e filho. A combinação de gráficos impressionantes, direção cinematográfica e excelente jogabilidade fez dele um dos jogos mais aclamados da geração.', '2018-04-20', 'Ação', 'PS4', 9.8, 1, 2),
 ('AaLwi_Z_iQo', 50.00, 'Marvels Spider-Man', 'Insomniac Games', 'Marvels Spider-Man coloca o jogador no papel de Peter Parker em uma aventura de mundo aberto pela cidade de Nova York. O jogo combina movimentação fluida através de teias, combate acrobático e uma narrativa original envolvendo diversos vilões clássicos do universo do Homem-Aranha. Além da história principal, há inúmeras atividades secundárias, colecionáveis e desafios espalhados pela cidade.', '2018-09-07', 'Ação', 'PS4', 9.6, 1, 2),
 ('9axpikOIHEo', 45.00, 'Horizon Zero Dawn', 'Guerrilla Games', 'Horizon Zero Dawn é um RPG de ação ambientado em um futuro distante onde máquinas gigantes dominam a natureza. O jogador controla Aloy, uma caçadora determinada a descobrir os segredos de seu passado e da queda da civilização. O jogo oferece exploração de mundo aberto, combate estratégico utilizando armas variadas e uma história repleta de mistérios sobre tecnologia e humanidade.', '2017-02-28', 'RPG', 'PS4', 9.2, 4, 2),
 ('QnDzJ9KzuV4', 40.00, 'Persona 5', 'Atlus', 'Persona 5 acompanha um grupo de estudantes conhecidos como Phantom Thieves, que utilizam poderes sobrenaturais para mudar os corações de indivíduos corruptos. O jogo mistura elementos de RPG por turnos, gerenciamento de tempo, relacionamentos sociais e exploração de masmorras. Seu estilo visual marcante, trilha sonora memorável e narrativa envolvente o transformaram em um dos RPGs mais celebrados de todos os tempos.', '2016-09-15', 'RPG', 'PS4', 9.7, 4, 2),
 ('W01L70IGBgE', 60.00, 'The Last of Us Part II', 'Naughty Dog', 'The Last of Us Part II continua a história de Ellie em um mundo pós-apocalíptico devastado por uma infecção mortal. O jogo explora temas de vingança, perda e sobrevivência através de uma narrativa intensa e emocional. Com gráficos extremamente detalhados, inteligência artificial avançada e combate brutal, a experiência oferece momentos marcantes e decisões difíceis ao longo da jornada.', '2020-06-19', 'Sobrevivência', 'PS4', 9.3, 8, 2),
 ('iqysmS4lxwQ', 55.00, 'Ghost of Tsushima', 'Sucker Punch Productions', 'Ghost of Tsushima é um jogo de ação em mundo aberto ambientado durante a invasão mongol do Japão feudal. O jogador controla Jin Sakai, um samurai que precisa abandonar tradições para proteger sua terra natal. O jogo oferece combates inspirados em duelos de samurai, exploração livre de paisagens deslumbrantes e uma narrativa focada em honra, sacrifício e resistência.', '2020-07-17', 'Aventura', 'PS4', 9.5, 2, 2),
 ('4qrOkLEJL9k', 40.00, 'Detroit Become Human', 'Quantic Dream', 'Detroit: Become Human é uma aventura narrativa ambientada em um futuro onde androides convivem com humanos. O jogador acompanha três protagonistas diferentes cujas escolhas influenciam diretamente o rumo da história. O jogo possui múltiplos finais, centenas de decisões importantes e explora temas como inteligência artificial, preconceito, liberdade e identidade.', '2018-05-25', 'Aventura', 'PS4', 9.1, 2, 2),
/*PS5*/
 ('ENf1yjCMpZo', 70.00, 'Marvels Spider-Man 2', 'Insomniac Games', 'Marvels Spider-Man 2 reúne Peter Parker e Miles Morales em uma nova aventura de mundo aberto por Nova York. O jogo introduz mecânicas inéditas de movimentação, novos poderes, troca rápida entre protagonistas e uma história envolvendo ameaças como Venom e Kraven. Com gráficos avançados, combate refinado e exploração mais dinâmica, o título expande significativamente tudo o que foi apresentado nos jogos anteriores da franquia.', '2023-10-20', 'Ação', 'PS5', 9.7, 1, 3),
 ('hfJ4Km46A-0', 70.00, 'God of War Ragnarök', 'Santa Monica Studio', 'God of War Ragnarök continua a jornada de Kratos e Atreus através dos Nove Reinos da mitologia nórdica enquanto se aproximam dos eventos do Ragnarök. O jogo amplia o sistema de combate, adiciona novas habilidades, inimigos e áreas exploráveis, além de aprofundar o desenvolvimento dos personagens e os conflitos entre deuses e mortais. Sua narrativa épica e produção de altíssima qualidade o tornaram um dos maiores lançamentos do PlayStation 5.', '2022-11-09', 'Ação', 'PS5', 9.8, 1, 3),
 ('2TMs2E6cms4', 70.00, 'Demons Souls', 'Bluepoint Games', 'Demons Souls é o remake completo do clássico RPG de ação que deu origem ao gênero Soulslike. O jogador explora o reino de Boletaria enfrentando criaturas aterrorizantes, chefes poderosos e desafios extremamente difíceis. O remake moderniza gráficos, animações e efeitos sonoros, mantendo a essência do jogo original enquanto aproveita o hardware do PlayStation 5.', '2020-11-12', 'RPG', 'PS5', 9.3, 4, 3),
 ('55PRv_e00wc', 60.00, 'Ratchet & Clank Rift Apart', 'Insomniac Games', 'Ratchet & Clank: Rift Apart é uma aventura de ação e plataforma que utiliza portais dimensionais para transportar os personagens instantaneamente entre diferentes mundos. O jogo apresenta armas criativas, cenários altamente detalhados e uma história divertida envolvendo múltiplas realidades. Seu visual impressionante e carregamentos praticamente instantâneos demonstram o potencial técnico do PlayStation 5.', '2021-06-11', 'Aventura', 'PS5', 9.2, 2, 3),
 ('gV5rIW1Qums', 70.00, 'Final Fantasy XVI', 'Square Enix', 'Final Fantasy XVI apresenta uma narrativa sombria ambientada no continente de Valisthea, onde nações entram em conflito pelo controle de recursos mágicos. O jogador acompanha Clive Rosfield em uma jornada repleta de batalhas épicas, intrigas políticas e criaturas lendárias conhecidas como Eikons. O combate em tempo real traz uma abordagem mais focada na ação sem abandonar os elementos clássicos da série.', '2023-06-22', 'RPG', 'PS5', 9.1, 4, 3),
 ('wHMNQzLG_Jg', 60.00, 'Astro Bot', 'Team Asobi', 'Astro Bot é um jogo de plataforma que explora ao máximo os recursos do controle DualSense e do PlayStation 5. O jogador embarca em uma aventura cheia de criatividade, fases variadas e referências à história da marca PlayStation. Com controles precisos, design de níveis excelente e muito carisma, o jogo rapidamente se tornou um dos maiores sucessos da plataforma.', '2024-09-06', 'Aventura', 'PS5', 9.6, 2, 3),
 ('DSznLWimMlU', 70.00, 'Stellar Blade', 'Shift Up', 'Stellar Blade é um RPG de ação ambientado em um futuro pós-apocalíptico onde a humanidade luta para recuperar a Terra de criaturas misteriosas. O jogador controla Eve em combates rápidos e desafiadores que exigem reflexos, esquivas precisas e domínio de combos. O jogo combina narrativa sci-fi, exploração e batalhas intensas contra chefes gigantescos.', '2024-04-26', 'Ação', 'PS5', 8.9, 1, 3),
 ('Lq594XmpPBg', 60.00, 'Horizon Forbidden West', 'Guerrilla Games', 'Horizon Forbidden West continua a história de Aloy enquanto ela viaja para o oeste proibido em busca de uma solução para uma nova ameaça global. O jogo expande o mundo aberto do título anterior com novas regiões, máquinas, mecânicas de exploração e combate. A aventura combina narrativa envolvente, visuais impressionantes e grande liberdade para o jogador.', '2022-02-18', 'RPG', 'PS5', 9.2, 4, 3),
 ('ov4fJmGCsZM', 60.00, 'Returnal', 'Housemarque', 'Returnal é um jogo de ação e ficção científica que mistura elementos roguelike com combate frenético em terceira pessoa. A protagonista Selene fica presa em um ciclo temporal em um planeta alienígena hostil, revivendo os mesmos eventos após cada morte. O jogo oferece progressão baseada em aprendizado, atmosfera misteriosa e desafios intensos.', '2021-04-30', 'Ação', 'PS5', 8.8, 1, 3),
 ('oz-O74SmTSQ', 70.00, 'Gran Turismo 7', 'Polyphony Digital', 'Gran Turismo 7 é um simulador de corrida que reúne centenas de veículos, pistas detalhadas e um sistema de física avançado voltado para realismo. O jogo oferece modos para iniciantes e veteranos, além de ampla personalização de carros e competições online. Sua atenção aos detalhes e paixão pela cultura automotiva fazem dele uma das principais referências do gênero.', '2022-03-04', 'Corrida', 'PS5', 9.0, 6, 3),
 ('dlQ3FeNu5Yw', 20.00, 'Alan Wake 2', 'Remedy Entertainment', 'Alan Wake é um thriller psicológico onde o escritor Alan Wake se vê preso em acontecimentos sobrenaturais inspirados em sua própria obra. O jogo mistura exploração, narrativa cinematográfica e combate contra entidades sombrias utilizando armas convencionais e luz como principal ferramenta de sobrevivência.', '2010-05-14', 'Terror', 'PS5', 8.9, 5, 3),
/*XBOX ONE*/
 ('Rh_NXwqFvHc', 40.00, 'Halo 5: Guardians', '343 Industries', 'Halo 5: Guardians continua a história do universo Halo apresentando um conflito entre Master Chief e o Spartan Locke. O jogo oferece uma campanha focada em esquadrões, novos equipamentos de mobilidade e um multiplayer extremamente competitivo. Seus modos Arena e Warzone expandem significativamente a experiência online da franquia, trazendo batalhas em larga escala e progressão constante.', '2015-10-27', 'Ação', 'Xbox One', 8.5, 1, 4),
 ('5xy4n73WOMM', 50.00, 'Forza Horizon 4', 'Playground Games', 'Forza Horizon 4 é um jogo de corrida em mundo aberto ambientado em uma versão fictícia do Reino Unido. O destaque principal são as estações do ano dinâmicas, que alteram completamente as condições das pistas e a exploração do mapa. Com centenas de veículos licenciados, eventos variados e um mundo vibrante, o jogo é considerado um dos melhores arcades de corrida já produzidos.', '2018-10-02', 'Corrida', 'Xbox One', 9.5, 6, 4),
 ('FYH9n37B7Yw', 60.00, 'Forza_Horizon 5', 'Playground Games', 'Forza Horizon 5 leva os jogadores para uma enorme representação do México, oferecendo ambientes variados como desertos, florestas, cidades históricas e vulcões. O jogo expande todas as mecânicas de seus antecessores, trazendo gráficos impressionantes, clima dinâmico, centenas de carros e inúmeras atividades online e offline.', '2021-11-09', 'Corrida', 'Xbox One', 9.6, 6, 4),
 ('APqBWniRQbQ', 50.00, 'Gears_5', 'The Coalition', 'Gears 5 acompanha Kait Diaz em uma jornada para descobrir a verdade sobre suas origens e sua ligação com a ameaça Swarm. O jogo apresenta campanha cinematográfica, modos cooperativos, multiplayer competitivo e áreas semiabertas para exploração. Com gráficos avançados e combate refinado, é um dos maiores títulos da franquia Gears.', '2019-09-10', 'Ação', 'Xbox One', 9.0, 1, 4),
 ('r5JIBaasuE8', 40.00, 'Sea of Thieves', 'Rare', 'Sea of Thieves é uma aventura multiplayer em mundo aberto onde os jogadores assumem o papel de piratas explorando oceanos repletos de ilhas, tesouros e perigos. O foco está na cooperação entre tripulantes, batalhas navais, caça a tesouros e histórias emergentes criadas pelos próprios jogadores durante suas jornadas.', '2018-03-20', 'Aventura', 'Xbox One', 8.9, 2, 4),
 ('kd0zbNw1VOg', 30.00, 'Ori_and_the_Will_of_the_Wisps', 'Moon Studios', 'Ori and the Will of the Wisps é uma aventura de plataforma e exploração que acompanha Ori em uma emocionante jornada por um mundo mágico e ameaçado pela escuridão. O jogo combina movimentação extremamente fluida, combate aprimorado, exploração estilo metroidvania e uma narrativa emocionante acompanhada por uma trilha sonora marcante.', '2020-03-11', 'Aventura', 'Xbox One', 9.7, 2, 4),
 ('MmB9b5njVbA', 30.00, 'Minecraft', 'Mojang Studios', 'Minecraft é um jogo de construção e sobrevivência que oferece liberdade quase ilimitada para explorar, coletar recursos, fabricar ferramentas e criar estruturas. Os jogadores podem enfrentar monstros, explorar cavernas, construir cidades inteiras ou simplesmente expressar sua criatividade em um mundo gerado proceduralmente. Seu impacto cultural o tornou um dos jogos mais vendidos da história.', '2014-09-05', 'Sobrevivência', 'Xbox One', 9.8, 8, 4),
 ('53MyR_Z3i1w', 50.00, 'The Witcher 3 Wild Hunt', 'CD Projekt Red', 'The Witcher 3: Wild Hunt acompanha Geralt de Rívia em uma busca por sua filha adotiva enquanto enfrenta monstros, guerras e forças sobrenaturais. O jogo apresenta um enorme mundo aberto repleto de missões detalhadas, escolhas com consequências significativas e personagens memoráveis. É amplamente considerado um dos maiores RPGs já criados.', '2015-05-19', 'RPG', 'Xbox One', 9.9, 4, 4),
 ('NN-9SQXoi50', 25.00, 'Cuphead', 'Studio MDHR', 'Cuphead é um jogo de ação inspirado nos desenhos animados da década de 1930, apresentando animações desenhadas à mão e trilha sonora baseada em jazz. O jogo é famoso por seus chefes desafiadores, combate preciso e visual único, exigindo reflexos rápidos e domínio das mecânicas para avançar.', '2017-09-29', 'Ação', 'Xbox One', 9.3, 1, 4),
 ('FqJdZQPBDF0', 25.00, 'Sunset Overdrive', 'Insomniac Games', 'Sunset Overdrive é um jogo de ação em mundo aberto ambientado em uma cidade dominada por mutantes criados por uma bebida energética contaminada. O jogador utiliza armas extravagantes, movimentação acrobática e trilhos espalhados pelo cenário para realizar combates rápidos e caóticos. Seu humor exagerado e gameplay criativo o tornaram um dos exclusivos mais marcantes do Xbox One.', '2014-10-28', 'Ação', 'Xbox One', 8.8, 1, 4),
/*XBOX SERIES S*/
 ('Fmdb-KmlzD8', 70.00, 'Halo Infinite', '343 Industries', 'Halo Infinite acompanha Master Chief em uma nova batalha contra os Banished em um gigantesco anel Halo parcialmente destruído. O jogo introduz áreas semiabertas para exploração, equipamentos inéditos como o gancho de agarrar e uma campanha focada em recuperar a esperança da humanidade. Além da história principal, o multiplayer gratuito oferece modos competitivos e cooperativos que expandem a experiência clássica da franquia.', '2021-12-08', 'Ação', 'Xbox Series S', 8.8, 1, 5),
 ('oYhaW-Vr4wg', 60.00, 'Forza Horizon 6', 'Playground Games', 'Forza Horizon 6 leva os jogadores para uma enorme representação do México, oferecendo desertos, florestas tropicais, cidades históricas, praias e vulcões. O jogo apresenta centenas de carros licenciados, clima dinâmico, eventos variados e um vasto mundo aberto repleto de atividades. Seus gráficos impressionantes e dirigibilidade refinada o colocam entre os melhores jogos de corrida da atualidade.', '2021-11-09', 'Corrida', 'Xbox Series S', 9.6, 6, 5),
 ('kfYEiTdsyas', 70.00, 'Starfield', 'Bethesda Game Studios', 'Starfield é um RPG de exploração espacial ambientado em um futuro onde a humanidade colonizou diversos sistemas estelares. O jogador cria seu próprio personagem, pilota naves, explora planetas, participa de conflitos políticos e descobre mistérios espalhados pela galáxia. O jogo oferece enorme liberdade de escolha, personalização detalhada e uma grande quantidade de missões e conteúdos opcionais.', '2023-09-06', 'RPG', 'Xbox Series S', 8.7, 4, 5),
 ('ciVgq5xO5G0', 40.00, 'Grounded', 'Obsidian Entertainment', 'Grounded é um jogo de sobrevivência onde os protagonistas são misteriosamente reduzidos ao tamanho de insetos e precisam sobreviver em um quintal transformado em um ambiente gigantesco e perigoso. O jogador coleta recursos, constrói bases, fabrica equipamentos e enfrenta criaturas como formigas, aranhas e besouros enquanto tenta descobrir a causa do fenômeno.', '2022-09-27', 'Sobrevivência', 'Xbox Series S', 8.9, 8, 5),
 ('mBi9rqCZ4os', 60.00, 'Psychonauts 2', 'Double Fine Productions', 'Psychonauts 2 acompanha Razputin Aquato em uma aventura dentro da mente de diferentes personagens, explorando cenários criativos que representam emoções, memórias e traumas. O jogo mistura plataforma, combate e resolução de puzzles enquanto desenvolve uma narrativa divertida e surpreendentemente profunda sobre saúde mental e crescimento pessoal.', '2021-08-25', 'Aventura', 'Xbox Series S', 9.3, 2, 5),
 ('O2i1Vq3Odbg', 50.00, 'Hi-Fi Rush', 'Tango Gameworks', 'Hi-Fi Rush é um jogo de ação onde praticamente tudo acontece no ritmo da música. O jogador controla Chai, um jovem que acaba envolvido em uma conspiração corporativa e utiliza ataques sincronizados com a trilha sonora para derrotar inimigos. O visual estilizado, a jogabilidade criativa e o humor leve fizeram dele uma das maiores surpresas dos últimos anos.', '2023-01-25', 'Ação', 'Xbox Series S', 9.2, 1, 5),
 ('3VYGOkMnGCE', 70.00, 'Senuas Saga Hellblade II', 'Ninja Theory', 'Senuas Saga: Hellblade II continua a jornada da guerreira Senua em uma aventura sombria inspirada na mitologia nórdica. O jogo combina narrativa cinematográfica, exploração e combates brutais enquanto retrata de forma intensa os conflitos psicológicos da protagonista. Seus gráficos extremamente avançados e sua atmosfera imersiva fazem dele uma das produções mais impressionantes da geração atual.', '2024-05-21', 'Aventura', 'Xbox Series S', 9.0, 2, 5);

SELECT * FROM USUARIO;
SELECT * FROM JOGOS;
SELECT * FROM CARRINHO;