CREATE DATABASE IF NOT EXISTS AssinaturaJogos;
USE AssinaturaJogos;

CREATE TABLE IF NOT EXISTS generos (
    id_genero INT AUTO_INCREMENT PRIMARY KEY,
    nome_genero VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS plataformas (
    id_plataforma INT AUTO_INCREMENT PRIMARY KEY,
    nome_plataforma VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario (
    id_user INT AUTO_INCREMENT,
    nome_user VARCHAR(50) NOT NULL,
    login_user VARCHAR(50) NOT NULL UNIQUE,
    senha_user VARCHAR(50) NOT NULL,
    email_user VARCHAR(50) NOT NULL UNIQUE,
    saldo INT DEFAULT 1000,
    PRIMARY KEY(id_user)
);

CREATE TABLE IF NOT EXISTS jogos (
    id_jogo INT AUTO_INCREMENT,
    video_jogo VARCHAR(255),
    preco_jogo DECIMAL(10,2) NOT NULL,
    nome_jogo VARCHAR(100) NOT NULL UNIQUE,
    criador_jogo VARCHAR(100) NOT NULL,
    descricao_jogo VARCHAR(2000) NOT NULL,
    data_lancamento DATE,
    genero VARCHAR(50),
    plataforma VARCHAR(50),
	nota_jogo Decimal(10,1) NOT NULL,
    id_genero INT NOT NULL,
    id_plataforma INT NOT NULL,
    PRIMARY KEY(id_jogo),
    FOREIGN KEY (id_genero) REFERENCES generos(id_genero),
    FOREIGN KEY (id_plataforma) REFERENCES plataformas(id_plataforma)
);
/*
CREATE TABLE IF NOT EXISTS itens_do_pedido (
    item_id INT AUTO_INCREMENT,
    pedido_id INT NOT NULL,
    id_jogo INT NOT NULL,
    id_plataforma INT NOT NULL,
    preco_na_venda DECIMAL(10,2),
    chave_de_ativacao VARCHAR(100),
    PRIMARY KEY(item_id),
    FOREIGN KEY(id_jogo) REFERENCES jogos(id_jogo),
    FOREIGN KEY(id_plataforma) REFERENCES plataformas(id_plataforma)
);
*/
create table if not exists carrinho(
id_carrinho INT PRIMARY KEY AUTO_INCREMENT,
id_jogo INT,
id_user INT,
FOREIGN KEY(id_jogo) REFERENCES jogos(id_jogo),
FOREIGN KEY(id_user) REFERENCES usuario(id_user)
);

CREATE TABLE IF NOT EXISTS biblioteca (
id_biblioteca INT PRIMARY KEY AUTO_INCREMENT,
id_jogo INT,
id_user INT,
data_compra DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(id_jogo) REFERENCES jogos(id_jogo),
FOREIGN KEY(id_user) REFERENCES usuario(id_user)    
);


INSERT INTO generos (nome_genero) VALUES
/*ID 1*/('Ação'),
/*ID 2*/('Aventura'),
/*ID 3*/('Luta'),
/*ID 4*/('RPG'),
/*ID 5*/('Terror'),
/*ID 6*/('Corrida'),
/*ID 7*/('Estrategia'),
/*ID 8*/('Sobrevivência'),
/*ID 9*/('Cartas'),
/*ID 10*/('Simulação');
INSERT INTO plataformas (nome_plataforma) VALUES
/*ID 1*/('PC'),
/*ID 2*/('PS1'),
/*ID 3*/('PS2'),
/*ID 4*/('PS3'),
/*ID 5*/('PS4'),
/*ID 6*/('PS5'),
/*ID 7*/('Xbox'),
/*ID 8*/('Xbox 360'),
/*ID 9*/('Xbox One'),
/*ID 10*/('Xbox Series S'),
/*ID 11*/('PSP');

INSERT INTO jogos (video_jogo, preco_jogo, nome_jogo, criador_jogo, descricao_jogo, data_lancamento, genero, plataforma, nota_jogo, id_genero, id_plataforma)
VALUES
/*PC*/
  ('uCaWqXP54Mc',49.99,'Uma_Musume_Pretty_Derby','Cygames','Uma Musume Pretty Derby é um jogo que mistura corrida, treinamento e elementos de RPG. O jogador assume o papel de treinador de garotas inspiradas em cavalos de corrida lendários da vida real, ajudando-as a desenvolver atributos, aprender habilidades e vencer competições cada vez mais difíceis. Além das corridas, o jogo apresenta histórias individuais para cada personagem, eventos especiais e apresentações musicais após as vitórias, criando uma experiência única para fãs de esportes, anime e gerenciamento.',   								    '2021-02-24','Corrida'   ,'PC',  8.5 ,6 ,1),
  ('7JFOLJv4s6Y',59.90,'Far_Cry_4',	'Ubisoft','Far Cry 4 é um jogo de ação e aventura em mundo aberto ambientado em Kyrat, uma região fictícia inspirada nos Himalaias. O jogador assume o papel de Ajay Ghale, que retorna à sua terra natal para cumprir o último desejo de sua mãe, mas acaba envolvido em uma guerra civil contra o tirânico rei Pagan Min. Com uma grande variedade de armas, veículos e atividades secundárias, o jogo oferece liberdade para explorar montanhas, florestas e fortalezas inimigas, permitindo diferentes estilos de combate, desde confrontos diretos até abordagens furtivas.',	'2014-11-18','Ação'      ,'PC',  8.7 ,1 ,1),	
  ('DfJaUpW_P00',39.90,'Lego_Batman','Traveller Tales','LEGO Batman: Legacy reúne o universo do Cavaleiro das Trevas em uma divertida aventura construída com peças LEGO. Os jogadores podem controlar Batman, Robin e diversos heróis e vilões da DC Comics enquanto enfrentam desafios, resolvem quebra-cabeças e participam de combates cheios de humor característicos da franquia LEGO. Com dezenas de personagens desbloqueáveis, fases inspiradas em momentos marcantes dos quadrinhos e animações divertidas, o jogo oferece entretenimento para jogadores de todas as idades.',    									'2008-09-23','Aventura'  ,'PC',  8.4 ,2 ,1),
  ('w8vPZrMFiZ4',59.99,'Honkai_Star_Rail','HoYoverse','Honkai: Star Rail é um RPG de turnos desenvolvido pela HoYoverse que leva os jogadores a uma aventura interplanetária a bordo do Expresso Astral. Durante a jornada, é possível conhecer diversos personagens com habilidades únicas, explorar diferentes mundos e enfrentar inimigos poderosos utilizando estratégias em combate. Com gráficos de alta qualidade, narrativa envolvente e atualizações frequentes, o jogo combina exploração, coleção de personagens e batalhas táticas em um universo de ficção científica.',												'2023-04-26','RPG'       ,'PC',  9.0 ,4 ,1),
  ('jkzRbc2VlXY',47.99,'Epic_Battle_Fantasy_5','Kupo Games','Epic Battle Fantasy 5 é um RPG por turnos indie que mistura combate estratégico com humor e referências a videogames clássicos (principalmente Final Fantasy e outros JRPGs). O jogo acompanha um grupo de personagens excêntricos (Matt, Natalie, Lance, Anna e NoLegs) em uma aventura cheia de batalhas, exploração e situações absurdas. O enredo começa com uma investigação sobre meteoros misteriosos e rapidamente evolui para eventos maiores envolvendo monólitos, criaturas corrompidas e ameaças cósmicas.',                      '2018-11-30','Aventura'  ,'PC',  9.0 ,2 ,1),
  ('CHAbHz8iYHc',18.70,'Plants_VS_Zombies','PopCap Games','Um jogo de ação-estratégia totalmente novo da PopCap, desenvolvedora de Bejeweled e Peggle! Zumbis estão invadindo seu lar e sua única defesa é seu arsenal de plantas! Armado com um viveiro de plantas exterminadoras de zumbis como atiradores de ervilha e bombas de cereja, você precisará pensar rápido e plantar mais rápido'                                                                                                                                                                                           ,                      '2009-05-05','Estrategia','PC', 9.5,7,1),                                                                       
  ('kWnzRGD9NDE', 19.99, 'Half-Life_2','Valve''Half-Life 2 é um dos jogos mais influentes da história dos videogames, trazendo uma experiência revolucionária de física aplicada, narrativa imersiva e gameplay em primeira pessoa extremamente fluido. O jogador controla Gordon Freeman em um mundo distópico dominado pela Combine, enfrentando soldados, criaturas alienígenas e resolvendo puzzles ambientais com a famosa Gravity Gun. O jogo se destaca pela ambientação, história cinematográfica e design de fases extremamente avançado para sua época.', '2004-11-16', 'Ação', 'PC', 9.8, 1, 1),
  ('JGhIXLO3ul8', 19.99, 'Dead_By_Daylight','Behaviour Interactive', 'Dead by Daylight é um jogo multiplayer assimétrico de terror onde quatro sobreviventes precisam escapar de um assassino enquanto trabalham juntos para consertar geradores e fugir do mapa. Cada partida é única devido aos diferentes killers, perks e mapas, criando uma experiência intensa e imprevisível. O jogo se destaca pela atmosfera sombria, colaboração entre jogadores e a tensão constante de perseguição.', '2016-06-14', 'Terror', 'PC', 8.5, 5, 1),
  ('7DbBwNpOkEI', 0.00, 'Yu-Gi-Oh!_Master_Duel','Konami','Yu-Gi-Oh! Master Duel é a versão digital oficial do famoso jogo de cartas colecionáveis, trazendo regras completas do TCG com milhares de cartas disponíveis. O jogo possui gráficos animados durante as invocações, sistema competitivo online ranqueado e eventos sazonais. É uma experiência estratégica profunda onde montagem de deck, leitura do oponente e timing são essenciais para vencer duelos.', '2022-01-19', 'Cartas', 'PC', 9.0, 9, 1),
  ('HLUY1nICQRY', 0.00, 'Genshin_Impact', 'HoYoverse', 'Genshin Impact é um RPG de mundo aberto com foco em exploração livre, combate elemental e narrativa expansiva. O jogador assume o papel do Viajante, que percorre o mundo de Teyvat em busca de seu irmão perdido, encontrando diversas nações inspiradas em culturas diferentes, cada uma com sua própria história, política e conflitos. O jogo se destaca pelo sistema de elementos que interagem entre si, permitindo combos estratégicos no combate, além de um vasto elenco de personagens jogáveis com habilidades únicas e um mundo vivo repleto de segredos, chefes e eventos constantes.', '2020-09-28', 'RPG', 'PC', 9.2, 4, 1),
  ('aeu87fKjV5w', 0.00, 'Zenless_Zone_Zero', 'HoYoverse', 'Zenless Zone Zero é um RPG de ação ambientado em um mundo futurista pós-apocalíptico onde a humanidade sobrevive após a destruição causada por fenômenos chamados Hollows. O jogador atua como um Proxy, guiando equipes de personagens em combates rápidos, estilizados e altamente dinâmicos dentro dessas dimensões perigosas. O jogo combina exploração urbana com missões de combate em tempo real, sistema de esquiva e combos rápidos, além de forte identidade visual inspirada em estética cyberpunk e animações fluidas.', '2024-07-04', 'Ação', 'PC', 8.8, 1, 1),
/*PS1*/
 ('EdHQlvbTQmc', 15.00, 'JoJos_Venture', 'Capcom', 'JoJos Venture é um jogo de luta baseado na famosa obra JoJos Bizarre Adventure, trazendo personagens icônicos do arco Stardust Crusaders em combates 2D intensos. O jogo se destaca pelo sistema de Stands, que permite ataques únicos e estratégicos, além de animações estilizadas e fidelidade ao material original. Cada personagem possui habilidades distintas, tornando as lutas imprevisíveis e cheias de personalidade.', '1998-10-01', 'Luta', 'PS1', 7.8, 3, 2),
 ('E0-C5h7n7RA', 10.00, 'Digimon_World', 'Bandai', 'Digimon World é um RPG de criação e sobrevivência onde o jogador cuida, treina e evolui Digimons em um mundo digital aberto e instável. O gameplay mistura exploração, gerenciamento de recursos e evolução de criaturas, exigindo atenção constante ao estado do Digimon, como fome, disciplina e felicidade. O jogo é conhecido por sua dificuldade e sistema de evolução não linear.', '1999-01-28', 'RPG', 'PS1', 8.2, 4, 2),
 ('SNVudSA23yA', 12.00, 'Yu-Gi-Oh!_Forbidden_Memories', 'Konami', 'Yu-Gi-Oh! Forbidden Memories é um jogo de cartas que adapta o universo do anime em batalhas estratégicas simplificadas, porém desafiadoras. O sistema de fusão de cartas é uma das principais mecânicas, permitindo criar monstros poderosos combinando cartas específicas. O jogo também apresenta uma campanha baseada no Egito antigo, com duelos contra personagens icônicos da série.', '1999-12-09', 'Cartas', 'PS1', 8.0, 9, 2),
 ('p0WwkDg6PdU', 18.00, 'Resident_Evil_3_Nemesis', 'Capcom', 'Resident Evil 3: Nemesis é um survival horror que coloca o jogador no meio do caos de Raccoon City durante o surto do T-Virus. O grande destaque é o perseguidor Nemesis, uma criatura implacável que caça a protagonista Jill Valentine ao longo do jogo. Com puzzles, gestão de recursos e atmosfera tensa, o jogo intensifica o terror e a sensação de desespero constante.', '1999-09-22', 'Terror', 'PS1', 9.1, 5, 2),
 ('n_pwOxMhhGs', 10.00, 'Crash_Bandicoot', 'Naughty Dog', 'Crash Bandicoot é um jogo de plataforma 3D com progressão linear, onde o jogador controla Crash em fases cheias de obstáculos, inimigos e desafios de precisão. O jogo se destaca pelo level design criativo, dificuldade progressiva e estilo carismático, sendo um dos maiores ícones do PS1.', '1996-09-09', 'Aventura', 'PS1', 8.5, 2, 2),
 ('TEN-p5e2WkM', 20.00, 'Final_Fantasy_VII', 'Square', 'Final Fantasy VII é um RPG clássico que acompanha Cloud Strife em uma jornada contra a corporação Shinra e o vilão Sephiroth. O jogo revolucionou a indústria com sua narrativa profunda, personagens marcantes e sistema de combate baseado em turnos com Materia, permitindo customização avançada de habilidades.', '1997-01-31', 'RPG', 'PS1', 9.7, 4, 2),
 ('5SA5VVBb2bU', 20.00, 'Metal_Gear_Solid', 'Konami', 'Metal Gear Solid é um jogo de espionagem tática que revolucionou o gênero stealth, colocando o jogador no papel de Solid Snake em uma missão para neutralizar ameaças nucleares. O jogo enfatiza furtividade, evitando combates diretos e utilizando estratégias inteligentes para passar pelos inimigos.', '1998-10-20', 'Ação', 'PS1', 9.6, 1, 2),
 ('kUjLG8ZxuHQ', 18.00, 'Resident_Evil_2', 'Capcom', 'Resident Evil 2 é um survival horror ambientado em Raccoon City durante o apocalipse zumbi, onde o jogador controla Leon Kennedy e Claire Redfield em campanhas separadas. O jogo combina exploração, puzzles e combate limitado, criando uma atmosfera de tensão constante.', '1998-01-21', 'Terror', 'PS1', 9.3, 5, 2),
 ('Ibbr_kbuIg4', 15.00, 'Gran_Turismo', 'Polyphony Digital', 'Gran Turismo é um simulador de corrida que revolucionou o gênero ao trazer física realista, grande variedade de carros licenciados e pistas detalhadas. O jogo possui modo carreira profundo onde o jogador evolui de iniciante até piloto profissional.', '1997-12-23', 'Corrida', 'PS1', 9.4, 6, 2),
 ('v7FYB1-aZQ4', 15.00, 'Castlevania_Symphony_of_the_Night', 'Konami', 'Castlevania: Symphony of the Night é um action RPG com exploração estilo metroidvania, onde o jogador controla Alucard explorando o castelo de Drácula. O jogo se destaca pela liberdade de exploração, progressão por habilidades e atmosfera gótica marcante.', '1997-03-20', 'Ação', 'PS1', 9.5, 1, 2),
/*PS2*/
  ('oe0OmX9hINA',49.90,'God_Of_War_II','Santa Monica','God of War II é um jogo de ação e aventura que continua a jornada de Kratos após sua ascensão ao posto de Deus da Guerra. Traído por Zeus e privado de seus poderes divinos, Kratos embarca em uma busca por vingança que o leva a enfrentar criaturas mitológicas, Titãs e os próprios deuses do Olimpo. Com combates intensos, quebra-cabeças desafiadores, batalhas épicas contra chefes gigantescos e uma narrativa marcante baseada na mitologia grega, o jogo é considerado um dos maiores clássicos do PlayStation 2.',           								 	'2007-03-13','Ação'      ,'PS2', 9.4 ,1 ,3),
  ('SCqjjgi2MJg',18.99,'Devil_May_Cry_3','Capcom','Devil May Cry 3 é um jogo de ação hack and slash que conta a origem da rivalidade entre os irmãos Dante e Vergil. Utilizando espadas, armas de fogo e diversos estilos de combate, os jogadores enfrentam hordas de demônios em batalhas rápidas e cheias de estilo. Conhecido por sua dificuldade desafiadora, chefes memoráveis e sistema de combos avançado, o jogo é considerado por muitos fãs como um dos melhores títulos da franquia Devil May Cry.',																											'2005-02-17','Ação'      ,'PS2', 9.5 ,1 ,3),
  ('6yzlmGQXQEs',25.00,'Dark_Cloud_2','Level-5','Dark Cloud 2, conhecido como Dark Chronicle em algumas regiões, é um RPG de ação que combina exploração de dungeons, combate em tempo real e um extenso sistema de construção de cidades. O jogador controla Max e Monica em uma aventura através do tempo para impedir a destruição do mundo causada por uma força maligna. Além do combate dinâmico, o jogo oferece criação de invenções, pesca, fotografia e diversos sistemas secundários que aumentam significativamente sua profundidade e longevidade.', '2002-11-28', 'RPG', 'PS2', 8.9, 4, 3),
  ('kfCVO20uEB0', 20.00,'God_Hand', 'Clover Studio', 'God Hand é um beat em up de ação conhecido por sua dificuldade elevada, humor absurdo e sistema de combate extremamente personalizável. O jogador controla Gene, um lutador que possui o lendário God Hand, enfrentando hordas de inimigos utilizando golpes, esquivas e combos criados pelo próprio jogador. O jogo ganhou status cult devido à sua jogabilidade única e desafiadora.', '2006-09-14', 'Ação', 'PS2', 8.8, 1, 3),
  ('CbHrBbHNQ', 30.00, 'GTA_San_Andreas', 'Rockstar Games', 'Grand Theft Auto: San Andreas é um jogo de ação e aventura em mundo aberto onde o jogador assume o papel de Carl Johnson, que retorna para sua cidade natal após anos longe. A história envolve disputas entre gangues, corrupção policial e ascensão no mundo do crime. O jogo oferece enorme liberdade de exploração, missões variadas, personalização de personagem, veículos e inúmeras atividades paralelas.', '2004-10-26', 'Ação', 'PS2', 9.8, 1, 3),
  ('1KTghW30ZuY', 30.00, 'Resident_Evil_4', 'Capcom', 'Resident Evil 4 acompanha Leon S. Kennedy em uma missão para resgatar a filha do presidente dos Estados Unidos em uma vila isolada da Europa. O jogo revolucionou os shooters em terceira pessoa com sua câmera sobre o ombro, combate intenso e ritmo equilibrado entre ação e terror. Sua influência pode ser vista em inúmeros jogos lançados posteriormente.', '2005-10-25', 'Terror', 'PS2', 9.9, 5, 3),
  ('Aza7OHTC5t0', 18.00, 'Chaos_Legion', 'Capcom', 'Chaos Legion é um jogo de ação hack and slash onde o jogador controla Sieg, um guerreiro capaz de invocar criaturas conhecidas como Legions para auxiliá-lo em combate. O sistema permite alternar entre diferentes Legions, cada uma especializada em estilos específicos de ataque, defesa ou suporte. O jogo apresenta atmosfera sombria inspirada em fantasia gótica.', '2003-06-26', 'Ação', 'PS2', 7.9, 1, 3),
  ('jnPRiX0fe8A', 25.00, 'Shadow_of_the_Colossus', 'Team Ico', 'Shadow of the Colossus é uma aventura única focada na derrota de gigantescos colossos espalhados por uma terra misteriosa e desolada. O jogador controla Wander em uma jornada para trazer uma jovem de volta à vida, enfrentando criaturas monumentais que funcionam como puzzles vivos. O jogo é amplamente elogiado por sua direção artística, trilha sonora e impacto emocional.', '2005-10-18', 'Aventura', 'PS2', 9.8, 2, 3),
  ('zCa8w6mrDJg', 25.00, 'Kingdom_Hearts_II', 'Square Enix', 'Kingdom Hearts II mistura personagens originais com universos da Disney e elementos da série Final Fantasy em uma aventura repleta de ação e emoção. O jogador controla Sora enquanto viaja entre diferentes mundos enfrentando os Heartless e a Organization XIII. O combate rápido, a narrativa ambiciosa e a variedade de cenários fazem do jogo um dos títulos mais populares da franquia.', '2005-12-22', 'RPG', 'PS2', 9.4, 4, 3),
  ('88KNf0MtU14', 20.00, 'Bully', 'Rockstar Games', 'Bully é um jogo de ação e aventura ambientado em um internato onde o jogador controla Jimmy Hopkins, um estudante problemático tentando sobreviver às rivalidades entre grupos de alunos. O jogo apresenta missões escolares, exploração livre do campus e da cidade, além de atividades como aulas, corridas de bicicleta e minigames. Sua abordagem única da vida escolar o tornou um clássico cult da Rockstar.', '2006-10-17', 'Aventura', 'PS2', 9.0, 2, 3),
/*PS3*/
('kE7li_u1nmg', 40.00, 'The Last of Us', 'Naughty Dog', 'The Last of Us é um jogo de ação e sobrevivência ambientado em um mundo devastado por uma infecção fúngica que transformou grande parte da humanidade em criaturas agressivas. O jogador acompanha Joel e Ellie em uma jornada perigosa pelos Estados Unidos, enfrentando infectados e grupos hostis. O jogo se destaca por sua narrativa emocional, personagens memoráveis, combate tenso e excelente desenvolvimento de relacionamento entre os protagonistas.', '2013-06-14', 'Sobrevivência', 'PS3', 9.9, 8, 4),
('tlkkceDkT88', 30.00, 'Uncharted 2: Among Thieves', 'Naughty Dog', 'Uncharted 2: Among Thieves acompanha o caçador de tesouros Nathan Drake em uma aventura repleta de ação, exploração e mistérios históricos. O jogo leva os jogadores por diversos locais exóticos ao redor do mundo em busca de um lendário artefato. Com cenas cinematográficas impressionantes, personagens carismáticos e sequências de ação memoráveis, é considerado um dos melhores jogos de aventura de sua geração.', '2009-10-13', 'Aventura', 'PS3', 9.7, 2, 4),
('MMUbcBbIXIA', 35.00, 'God of War III', 'Santa Monica Studio', 'God of War III conclui a saga grega de Kratos em uma jornada brutal de vingança contra os deuses do Olimpo. O jogo apresenta batalhas épicas contra criaturas mitológicas gigantescas, combate intenso e gráficos impressionantes para a época. A escala dos confrontos e a violência característica da série tornaram este título um dos maiores destaques do PlayStation 3.', '2010-03-16', 'Ação', 'PS3', 9.6, 1, 4),
('FRnIyXvonAU', 30.00, 'Demons_Souls', 'FromSoftware', 'Demons Souls é um RPG de ação conhecido por sua dificuldade elevada, atmosfera sombria e sistema de progressão desafiador. O jogador explora o reino de Boletaria enfrentando monstros, demônios e chefes poderosos enquanto coleta almas para evoluir seu personagem. O jogo estabeleceu as bases do gênero Soulslike e influenciou profundamente a indústria dos videogames.', '2009-02-05', 'RPG', 'PS3', 9.4, 4, 4),
('fFfdSRMpQs', 20.00, 'LittleBigPlanet', 'Media Molecule', 'LittleBigPlanet é um jogo de plataforma criativo onde os jogadores controlam Sackboy em fases coloridas e cheias de desafios. Além da campanha principal, o jogo oferece poderosas ferramentas de criação que permitem construir fases, compartilhar conteúdos online e experimentar criações feitas pela comunidade.', '2008-10-27', 'Aventura', 'PS3', 9.0, 2, 4),
('EMCkbDnaTDM', 25.00, 'Metal Gear Rising: Revengeance', 'PlatinumGames', 'Metal Gear Rising: Revengeance coloca o jogador no controle de Raiden em um jogo focado em ação rápida e combate com espadas. O sistema de corte livre permite dividir praticamente qualquer objeto ou inimigo em tempo real. O jogo combina narrativa exagerada, batalhas espetaculares e uma trilha sonora extremamente marcante.', '2013-02-19', 'Ação', 'PS3', 9.1, 1, 4),
('9cwNtyfdiaE', 20.00, 'inFAMOUS', 'Sucker Punch Productions', 'inFAMOUS acompanha Cole MacGrath após um misterioso evento conceder poderes elétricos extraordinários. O jogador pode escolher agir como herói ou vilão, alterando missões, habilidades e a percepção da população. O jogo mistura exploração em mundo aberto, combate com superpoderes e decisões morais que influenciam a narrativa.', '2009-05-26', 'Ação', 'PS3', 8.8, 1, 4),
('MXh25i7_3Is', 25.00, 'Gran Turismo 5', 'Polyphony Digital', 'Gran Turismo 5 é um simulador de corrida focado em realismo, oferecendo centenas de veículos licenciados e diversas pistas ao redor do mundo. O jogo apresenta física detalhada, sistema de danos, mudanças climáticas e competições que agradam tanto jogadores casuais quanto fãs de automobilismo.', '2010-11-24', 'Corrida', 'PS3', 8.9, 6, 4),
('b-4HNmuEAKg', 25.00, 'Killzone 2', 'Guerrilla Games', 'Killzone 2 é um shooter em primeira pessoa que coloca os jogadores em uma guerra brutal contra o exército Helghast. O jogo impressionou por seus gráficos avançados, efeitos visuais detalhados e atmosfera militar intensa. Sua campanha oferece combates pesados e cenários devastados pela guerra.', '2009-02-27', 'Ação', 'PS3', 8.7, 1, 4),
('mU3nNT4rcFg', 15.00, 'Journey', 'Thatgamecompany', 'Journey é uma experiência de aventura artística onde o jogador atravessa um vasto deserto em direção a uma montanha distante. O jogo utiliza narrativa visual e trilha sonora para transmitir emoções sem depender de diálogos. Seu sistema multiplayer permite encontros anônimos entre jogadores, criando momentos únicos de cooperação e descoberta.', '2012-03-13', 'Aventura', 'PS3', 9.3, 2, 4),
/*PS4*/
  ('BY9-jWQQHgw',191.59,'Five_Nights_at_Freddys_Security_Breach','Steel Wool Studios','Five Nights at Freddys: Security Breach é um jogo de terror e sobrevivência ambientado em um enorme centro de entretenimento chamado Mega Pizzaplex. O jogador controla Gregory, uma criança presa dentro do local durante a noite, que precisa escapar dos animatrônicos enquanto desvenda os mistérios do estabelecimento. Diferente dos jogos anteriores da série, Security Breach oferece exploração livre em um ambiente tridimensional, perseguições intensas e diversas áreas para investigar.',																	'2021-12-16','Terror'    ,'PS4', 6.0 ,5 ,5),
  ('CRLglREYEDs',39.99,'Shadow_of_Mordor','Monolith Productions','Middle-earth: Shadow of Mordor é um jogo de ação e aventura ambientado no universo de O Senhor dos Anéis. O jogador controla Talion, um guardião que retorna da morte em busca de vingança contra as forças de Sauron. O grande destaque do jogo é o Sistema Nêmesis, que permite que inimigos sobrevivam aos confrontos, evoluam em poder e desenvolvam rivalidades únicas com o jogador. Com combate dinâmico, exploração em mundo aberto e elementos de furtividade, o jogo oferece uma experiência marcante para fãs da Terra-média.',									'2014-09-30','Ação'      ,'PS4', 8.5 ,1 ,5),
  ('JnUbg-9v_bE', 39.99, 'Dragon_Ball_Xenoverse_2','Bandai Namco','Dragon Ball Xenoverse 2 é um RPG de ação baseado no universo de Dragon Ball, onde o jogador cria seu próprio personagem e participa de batalhas icônicas da série, alterando eventos da história original. O jogo possui combates em arena 3D, customização profunda de personagens, habilidades especiais e exploração de cidades como Conton City. Ele também conta com modo online, missões cooperativas e diversos DLCs com personagens adicionais.', '2016-10-25', 'Luta', 'PS4', 8.7, 3, 5),
  ('GodOfWar2018TrailerID', 50.00, 'God of War', 'Santa Monica Studio', 'God of War reinventa a franquia ao transportar Kratos para o mundo da mitologia nórdica. Agora acompanhado por seu filho Atreus, ele embarca em uma jornada para cumprir o último desejo de sua esposa. O jogo apresenta um sistema de combate mais estratégico e brutal, exploração semiaberta, evolução de equipamentos e uma narrativa emocionante centrada na relação entre pai e filho. A combinação de gráficos impressionantes, direção cinematográfica e excelente jogabilidade fez dele um dos jogos mais aclamados da geração.', '2018-04-20', 'Ação', 'PS4', 9.8, 1, 5),
  ('SpiderManPS4TrailerID', 50.00, 'Marvels Spider-Man', 'Insomniac Games', 'Marvels Spider-Man coloca o jogador no papel de Peter Parker em uma aventura de mundo aberto pela cidade de Nova York. O jogo combina movimentação fluida através de teias, combate acrobático e uma narrativa original envolvendo diversos vilões clássicos do universo do Homem-Aranha. Além da história principal, há inúmeras atividades secundárias, colecionáveis e desafios espalhados pela cidade.', '2018-09-07', 'Ação', 'PS4', 9.6, 1, 5),
  ('HorizonZeroDawnTrailerID', 45.00, 'Horizon Zero Dawn', 'Guerrilla Games', 'Horizon Zero Dawn é um RPG de ação ambientado em um futuro distante onde máquinas gigantes dominam a natureza. O jogador controla Aloy, uma caçadora determinada a descobrir os segredos de seu passado e da queda da civilização. O jogo oferece exploração de mundo aberto, combate estratégico utilizando armas variadas e uma história repleta de mistérios sobre tecnologia e humanidade.', '2017-02-28', 'RPG', 'PS4', 9.2, 4, 5),
  ('Persona5TrailerID', 40.00, 'Persona 5', 'Atlus', 'Persona 5 acompanha um grupo de estudantes conhecidos como Phantom Thieves, que utilizam poderes sobrenaturais para mudar os corações de indivíduos corruptos. O jogo mistura elementos de RPG por turnos, gerenciamento de tempo, relacionamentos sociais e exploração de masmorras. Seu estilo visual marcante, trilha sonora memorável e narrativa envolvente o transformaram em um dos RPGs mais celebrados de todos os tempos.', '2016-09-15', 'RPG', 'PS4', 9.7, 4, 5),
  ('TheLastOfUsPartIITrailerID', 60.00, 'The Last of Us Part II', 'Naughty Dog', 'The Last of Us Part II continua a história de Ellie em um mundo pós-apocalíptico devastado por uma infecção mortal. O jogo explora temas de vingança, perda e sobrevivência através de uma narrativa intensa e emocional. Com gráficos extremamente detalhados, inteligência artificial avançada e combate brutal, a experiência oferece momentos marcantes e decisões difíceis ao longo da jornada.', '2020-06-19', 'Sobrevivência', 'PS4', 9.3, 8, 5),
  ('GhostOfTsushimaTrailerID', 55.00, 'Ghost of Tsushima', 'Sucker Punch Productions', 'Ghost of Tsushima é um jogo de ação em mundo aberto ambientado durante a invasão mongol do Japão feudal. O jogador controla Jin Sakai, um samurai que precisa abandonar tradições para proteger sua terra natal. O jogo oferece combates inspirados em duelos de samurai, exploração livre de paisagens deslumbrantes e uma narrativa focada em honra, sacrifício e resistência.', '2020-07-17', 'Aventura', 'PS4', 9.5, 2, 5),
  ('DetroitBecomeHumanTrailerID', 40.00, 'Detroit Become Human', 'Quantic Dream', 'Detroit: Become Human é uma aventura narrativa ambientada em um futuro onde androides convivem com humanos. O jogador acompanha três protagonistas diferentes cujas escolhas influenciam diretamente o rumo da história. O jogo possui múltiplos finais, centenas de decisões importantes e explora temas como inteligência artificial, preconceito, liberdade e identidade.', '2018-05-25', 'Aventura', 'PS4', 9.1, 2, 5),
/*PS5*/
('SpiderMan2TrailerID', 70.00, 'Marvels Spider-Man 2', 'Insomniac Games', 'Marvels Spider-Man 2 reúne Peter Parker e Miles Morales em uma nova aventura de mundo aberto por Nova York. O jogo introduz mecânicas inéditas de movimentação, novos poderes, troca rápida entre protagonistas e uma história envolvendo ameaças como Venom e Kraven. Com gráficos avançados, combate refinado e exploração mais dinâmica, o título expande significativamente tudo o que foi apresentado nos jogos anteriores da franquia.', '2023-10-20', 'Ação', 'PS5', 9.7, 1, 6),
('GodOfWarRagnarokTrailerID', 70.00, 'God of War Ragnarök', 'Santa Monica Studio', 'God of War Ragnarök continua a jornada de Kratos e Atreus através dos Nove Reinos da mitologia nórdica enquanto se aproximam dos eventos do Ragnarök. O jogo amplia o sistema de combate, adiciona novas habilidades, inimigos e áreas exploráveis, além de aprofundar o desenvolvimento dos personagens e os conflitos entre deuses e mortais. Sua narrativa épica e produção de altíssima qualidade o tornaram um dos maiores lançamentos do PlayStation 5.', '2022-11-09', 'Ação', 'PS5', 9.8, 1, 6),
('DemonsSoulsRemakeTrailerID', 70.00, 'Demons Souls', 'Bluepoint Games', 'Demons Souls é o remake completo do clássico RPG de ação que deu origem ao gênero Soulslike. O jogador explora o reino de Boletaria enfrentando criaturas aterrorizantes, chefes poderosos e desafios extremamente difíceis. O remake moderniza gráficos, animações e efeitos sonoros, mantendo a essência do jogo original enquanto aproveita o hardware do PlayStation 5.', '2020-11-12', 'RPG', 'PS5', 9.3, 4, 6),
('RatchetClankRiftApartTrailerID', 60.00, 'Ratchet & Clank: Rift Apart', 'Insomniac Games', 'Ratchet & Clank: Rift Apart é uma aventura de ação e plataforma que utiliza portais dimensionais para transportar os personagens instantaneamente entre diferentes mundos. O jogo apresenta armas criativas, cenários altamente detalhados e uma história divertida envolvendo múltiplas realidades. Seu visual impressionante e carregamentos praticamente instantâneos demonstram o potencial técnico do PlayStation 5.', '2021-06-11', 'Aventura', 'PS5', 9.2, 2, 6),
('FFXVITrailerID', 70.00, 'Final Fantasy XVI', 'Square Enix', 'Final Fantasy XVI apresenta uma narrativa sombria ambientada no continente de Valisthea, onde nações entram em conflito pelo controle de recursos mágicos. O jogador acompanha Clive Rosfield em uma jornada repleta de batalhas épicas, intrigas políticas e criaturas lendárias conhecidas como Eikons. O combate em tempo real traz uma abordagem mais focada na ação sem abandonar os elementos clássicos da série.', '2023-06-22', 'RPG', 'PS5', 9.1, 4, 6),
('AstroBotTrailerID', 60.00, 'Astro Bot', 'Team Asobi', 'Astro Bot é um jogo de plataforma que explora ao máximo os recursos do controle DualSense e do PlayStation 5. O jogador embarca em uma aventura cheia de criatividade, fases variadas e referências à história da marca PlayStation. Com controles precisos, design de níveis excelente e muito carisma, o jogo rapidamente se tornou um dos maiores sucessos da plataforma.', '2024-09-06', 'Aventura', 'PS5', 9.6, 2, 6),
('StellarBladeTrailerID', 70.00, 'Stellar Blade', 'Shift Up', 'Stellar Blade é um RPG de ação ambientado em um futuro pós-apocalíptico onde a humanidade luta para recuperar a Terra de criaturas misteriosas. O jogador controla Eve em combates rápidos e desafiadores que exigem reflexos, esquivas precisas e domínio de combos. O jogo combina narrativa sci-fi, exploração e batalhas intensas contra chefes gigantescos.', '2024-04-26', 'Ação', 'PS5', 8.9, 1, 6),
('HorizonForbiddenWestTrailerID', 60.00, 'Horizon Forbidden West', 'Guerrilla Games', 'Horizon Forbidden West continua a história de Aloy enquanto ela viaja para o oeste proibido em busca de uma solução para uma nova ameaça global. O jogo expande o mundo aberto do título anterior com novas regiões, máquinas, mecânicas de exploração e combate. A aventura combina narrativa envolvente, visuais impressionantes e grande liberdade para o jogador.', '2022-02-18', 'RPG', 'PS5', 9.2, 4, 6),
('ReturnalTrailerID', 60.00, 'Returnal', 'Housemarque', 'Returnal é um jogo de ação e ficção científica que mistura elementos roguelike com combate frenético em terceira pessoa. A protagonista Selene fica presa em um ciclo temporal em um planeta alienígena hostil, revivendo os mesmos eventos após cada morte. O jogo oferece progressão baseada em aprendizado, atmosfera misteriosa e desafios intensos.', '2021-04-30', 'Ação', 'PS5', 8.8, 1, 6),
('GranTurismo7TrailerID', 70.00, 'Gran Turismo 7', 'Polyphony Digital', 'Gran Turismo 7 é um simulador de corrida que reúne centenas de veículos, pistas detalhadas e um sistema de física avançado voltado para realismo. O jogo oferece modos para iniciantes e veteranos, além de ampla personalização de carros e competições online. Sua atenção aos detalhes e paixão pela cultura automotiva fazem dele uma das principais referências do gênero.', '2022-03-04', 'Corrida', 'PS5', 9.0, 6, 6),
/*XBOX*/
('HaloCombatEvolvedTrailerID', 20.00, 'Halo: Combat Evolved', 'Bungie', 'Halo: Combat Evolved é um shooter em primeira pessoa que revolucionou o gênero nos consoles ao apresentar controles refinados, inteligência artificial avançada e uma campanha épica de ficção científica. O jogador assume o papel do Master Chief, um supersoldado encarregado de enfrentar a aliança alienígena Covenant enquanto descobre os mistérios de uma gigantesca estrutura conhecida como Halo. O jogo se tornou um dos maiores símbolos da marca Xbox.', '2001-11-15', 'Ação', 'Xbox', 9.7, 1, 7),
('Halo2TrailerID', 25.00, 'Halo 2', 'Bungie', 'Halo 2 expande a história do universo Halo ao apresentar novos personagens, conflitos políticos e batalhas em escala ainda maior. Além da campanha, o jogo revolucionou o multiplayer online nos consoles através do Xbox Live, estabelecendo padrões que influenciam jogos competitivos até hoje. Sua narrativa, trilha sonora e jogabilidade fizeram dele um dos títulos mais importantes da geração.', '2004-11-09', 'Ação', 'Xbox', 9.6, 1, 7),
('FableTrailerID', 20.00, 'Fable', 'Big Blue Box Studios', 'Fable é um RPG de fantasia onde as escolhas do jogador influenciam diretamente a aparência, reputação e destino do protagonista. Ambientado no reino de Albion, o jogo oferece liberdade para seguir o caminho do herói ou do vilão, além de missões variadas, evolução de habilidades e interação com diversos personagens. Seu sistema de consequências foi inovador para a época.', '2004-09-14', 'RPG', 'Xbox', 9.0, 4, 7),
('NinjaGaidenBlackTrailerID', 20.00, 'Ninja Gaiden Black', 'Team Ninja', 'Ninja Gaiden Black é um jogo de ação extremamente desafiador que acompanha o ninja Ryu Hayabusa em sua luta contra forças demoníacas e inimigos poderosos. O combate rápido, técnico e brutal exige domínio de esquivas, combos e diferentes armas. Considerado por muitos como uma das melhores versões de Ninja Gaiden, o jogo é lembrado por sua dificuldade e qualidade de gameplay.', '2005-09-20', 'Ação', 'Xbox', 9.4, 1, 7),
('ProjectGothamRacing2TrailerID', 15.00, 'Project Gotham Racing 2', 'Bizarre Creations', 'Project Gotham Racing 2 é um jogo de corrida que recompensa não apenas a velocidade, mas também o estilo de pilotagem através do sistema Kudos. Com diversos veículos licenciados, pistas inspiradas em cidades reais e modos multiplayer competitivos, o jogo se tornou uma das principais franquias de corrida do Xbox original.', '2003-11-04', 'Corrida', 'Xbox', 8.8, 6, 7),
('JetSetRadioFutureTrailerID', 15.00, 'Jet Set Radio Future', 'Smilebit', 'Jet Set Radio Future é um jogo de ação e aventura focado em patinação, exploração urbana e arte de rua. O jogador participa de disputas entre gangues enquanto realiza manobras radicais e espalha grafites por uma cidade futurista. Seu estilo visual cel-shading e trilha sonora marcante ajudaram a torná-lo um clássico cult.', '2002-02-22', 'Aventura', 'Xbox', 9.1, 2, 7),
('KOTORTrailerID', 20.00, 'Star Wars: Knights of the Old Republic', 'BioWare', 'Star Wars: Knights of the Old Republic é um RPG ambientado milhares de anos antes dos filmes da saga Star Wars. O jogador cria seu próprio personagem e toma decisões que influenciam sua jornada para o lado luminoso ou sombrio da Força. Com narrativa profunda, companheiros memoráveis e múltiplos finais, é considerado um dos melhores RPGs já produzidos.', '2003-07-15', 'RPG', 'Xbox', 9.7, 4, 7),
('SplinterCellTrailerID', 15.00, 'Tom Clancys Splinter Cell', 'Ubisoft Montreal', 'Splinter Cell coloca o jogador no papel do agente secreto Sam Fisher em missões de espionagem focadas em furtividade. O jogo exige planejamento, observação e uso inteligente de equipamentos tecnológicos para evitar detecção e completar objetivos. Sua iluminação dinâmica e mecânicas stealth foram altamente inovadoras para a época.', '2002-11-17', 'Ação', 'Xbox', 9.0, 1, 7),
('DeadOrAlive3TrailerID', 15.00, 'Dead or Alive 3', 'Team Ninja', 'Dead or Alive 3 é um jogo de luta conhecido por seu sistema de contra-ataques, arenas interativas e combate rápido. O título apresenta diversos lutadores com estilos distintos e gráficos impressionantes para o lançamento do Xbox original. Sua acessibilidade e profundidade competitiva ajudaram a consolidar a franquia.', '2001-11-15', 'Luta', 'Xbox', 8.7, 3, 7),
('MorrowindTrailerID', 20.00, 'The Elder Scrolls III: Morrowind', 'Bethesda Game Studios', 'The Elder Scrolls III: Morrowind é um RPG de mundo aberto ambientado na misteriosa ilha de Vvardenfell. O jogador possui enorme liberdade para explorar, completar missões, desenvolver habilidades e moldar seu próprio destino. O jogo é conhecido por sua profundidade, quantidade de conteúdo e influência duradoura sobre o gênero RPG ocidental.', '2002-06-06', 'RPG', 'Xbox', 9.5, 4, 7),
/*XBOX 360*/
('Halo3TrailerID', 30.00, 'Halo 3', 'Bungie', 'Halo 3 conclui a trilogia original de Master Chief em uma guerra épica contra o Covenant e a ameaça dos Flood. O jogo apresenta uma campanha repleta de batalhas memoráveis, veículos, armas icônicas e cenários grandiosos. Seu multiplayer competitivo se tornou um fenômeno mundial, ajudando a definir os jogos online nos consoles durante a geração Xbox 360.', '2007-09-25', 'Ação', 'Xbox 360', 9.8, 1, 8),
('GearsOfWarTrailerID', 25.00, 'Gears of War', 'Epic Games', 'Gears of War coloca os jogadores no papel de Marcus Fenix em uma luta desesperada contra a raça subterrânea conhecida como Locust. O jogo revolucionou os shooters em terceira pessoa com seu sistema de cobertura, combate intenso e visual impressionante. Sua atmosfera de guerra brutal e modo cooperativo ajudaram a transformá-lo em uma das principais franquias do Xbox.', '2006-11-07', 'Ação', 'Xbox 360', 9.5, 1, 8),
('GearsOfWar2TrailerID', 30.00, 'Gears of War 2', 'Epic Games', 'Gears of War 2 expande a guerra contra os Locust com batalhas ainda maiores, novos inimigos e uma narrativa mais emocional. O jogo aprimora praticamente todos os aspectos do original, oferecendo mais armas, modos multiplayer e momentos cinematográficos marcantes. É considerado um dos melhores exclusivos da geração Xbox 360.', '2008-11-07', 'Ação', 'Xbox 360', 9.4, 1, 8),
('ForzaMotorsport4TrailerID', 25.00, 'Forza Motorsport 4', 'Turn 10 Studios', 'Forza Motorsport 4 é um simulador de corrida focado em realismo, oferecendo centenas de veículos licenciados, física detalhada e diversas pistas famosas ao redor do mundo. O jogo apresenta grande atenção aos detalhes dos carros e uma experiência que agrada tanto jogadores casuais quanto fãs de automobilismo.', '2011-10-11', 'Corrida', 'Xbox 360', 9.2, 6, 8),
('SkyrimTrailerID', 30.00, 'The Elder Scrolls V: Skyrim', 'Bethesda Game Studios', 'Skyrim é um RPG de mundo aberto ambientado na região gelada de Skyrim, onde o jogador assume o papel do Dragonborn, um herói capaz de absorver almas de dragões. O jogo oferece liberdade quase total para explorar, completar missões, aprender magia, evoluir habilidades e moldar sua própria aventura em um mundo gigantesco repleto de segredos.', '2011-11-11', 'RPG', 'Xbox 360', 9.8, 4, 8),
('RedDeadRedemptionTrailerID', 30.00, 'Red Dead Redemption', 'Rockstar San Diego', 'Red Dead Redemption acompanha John Marston, um ex-fora-da-lei forçado a caçar antigos membros de sua gangue para proteger sua família. Ambientado no fim da era do Velho Oeste, o jogo oferece um enorme mundo aberto, missões envolventes, caçadas, duelos e uma narrativa considerada uma das melhores da indústria dos videogames.', '2010-05-18', 'Aventura', 'Xbox 360', 9.7, 2, 8),
('Fable2TrailerID', 20.00, 'Fable II', 'Lionhead Studios', 'Fable II é um RPG ambientado no reino de Albion, onde as decisões do jogador influenciam diretamente o desenvolvimento da história e do personagem. O jogo oferece liberdade para seguir diferentes estilos de combate, comprar propriedades, formar relacionamentos e escolher entre caminhos heroicos ou malignos.', '2008-10-21', 'RPG', 'Xbox 360', 9.0, 4, 8),
('Left4DeadTrailerID', 20.00, 'Left 4 Dead', 'Valve', 'Left 4 Dead é um jogo cooperativo de sobrevivência contra hordas de infectados. Os jogadores precisam trabalhar em equipe para atravessar mapas perigosos enquanto enfrentam criaturas especiais que exigem coordenação e estratégia. O sistema de inteligência artificial conhecido como Director garante que cada partida seja diferente.', '2008-11-18', 'Sobrevivência', 'Xbox 360', 9.3, 8, 8),
('MassEffect2TrailerID', 25.00, 'Mass Effect 2', 'BioWare', 'Mass Effect 2 é um RPG de ficção científica que coloca o jogador no papel do Comandante Shepard em uma missão suicida para salvar a galáxia de uma ameaça misteriosa. O jogo combina combate em terceira pessoa, escolhas morais, desenvolvimento de personagens e relacionamentos complexos com membros da tripulação.', '2010-01-26', 'RPG', 'Xbox 360', 9.7, 4, 8),
('AlanWakeTrailerID', 20.00, 'Alan Wake', 'Remedy Entertainment', 'Alan Wake é um thriller psicológico onde o escritor Alan Wake se vê preso em acontecimentos sobrenaturais inspirados em sua própria obra. O jogo mistura exploração, narrativa cinematográfica e combate contra entidades sombrias utilizando armas convencionais e luz como principal ferramenta de sobrevivência.', '2010-05-14', 'Terror', 'Xbox 360', 8.9, 5, 8),
/*XBOX ONE*/
('Halo5GuardiansTrailerID', 40.00, 'Halo 5: Guardians', '343 Industries', 'Halo 5: Guardians continua a história do universo Halo apresentando um conflito entre Master Chief e o Spartan Locke. O jogo oferece uma campanha focada em esquadrões, novos equipamentos de mobilidade e um multiplayer extremamente competitivo. Seus modos Arena e Warzone expandem significativamente a experiência online da franquia, trazendo batalhas em larga escala e progressão constante.', '2015-10-27', 'Ação', 'Xbox One', 8.5, 1, 9),
('ForzaHorizon4TrailerID', 50.00, 'Forza Horizon 4', 'Playground Games', 'Forza Horizon 4 é um jogo de corrida em mundo aberto ambientado em uma versão fictícia do Reino Unido. O destaque principal são as estações do ano dinâmicas, que alteram completamente as condições das pistas e a exploração do mapa. Com centenas de veículos licenciados, eventos variados e um mundo vibrante, o jogo é considerado um dos melhores arcades de corrida já produzidos.', '2018-10-02', 'Corrida', 'Xbox One', 9.5, 6, 9),
('ForzaHorizon5TrailerID', 60.00, 'Forza_Horizon 5', 'Playground Games', 'Forza Horizon 5 leva os jogadores para uma enorme representação do México, oferecendo ambientes variados como desertos, florestas, cidades históricas e vulcões. O jogo expande todas as mecânicas de seus antecessores, trazendo gráficos impressionantes, clima dinâmico, centenas de carros e inúmeras atividades online e offline.', '2021-11-09', 'Corrida', 'Xbox One', 9.6, 6, 9),
('Gears5TrailerID', 50.00, 'Gears_5', 'The Coalition', 'Gears 5 acompanha Kait Diaz em uma jornada para descobrir a verdade sobre suas origens e sua ligação com a ameaça Swarm. O jogo apresenta campanha cinematográfica, modos cooperativos, multiplayer competitivo e áreas semiabertas para exploração. Com gráficos avançados e combate refinado, é um dos maiores títulos da franquia Gears.', '2019-09-10', 'Ação', 'Xbox One', 9.0, 1, 9),
('SeaOfThievesTrailerID', 40.00, 'Sea of Thieves', 'Rare', 'Sea of Thieves é uma aventura multiplayer em mundo aberto onde os jogadores assumem o papel de piratas explorando oceanos repletos de ilhas, tesouros e perigos. O foco está na cooperação entre tripulantes, batalhas navais, caça a tesouros e histórias emergentes criadas pelos próprios jogadores durante suas jornadas.', '2018-03-20', 'Aventura', 'Xbox One', 8.9, 2, 9),
('OriWillOfTheWispsTrailerID', 30.00, 'Ori_and_the_Will_of_the_Wisps', 'Moon Studios', 'Ori and the Will of the Wisps é uma aventura de plataforma e exploração que acompanha Ori em uma emocionante jornada por um mundo mágico e ameaçado pela escuridão. O jogo combina movimentação extremamente fluida, combate aprimorado, exploração estilo metroidvania e uma narrativa emocionante acompanhada por uma trilha sonora marcante.', '2020-03-11', 'Aventura', 'Xbox One', 9.7, 2, 9),
('MinecraftTrailerID', 30.00, 'Minecraft', 'Mojang Studios', 'Minecraft é um jogo de construção e sobrevivência que oferece liberdade quase ilimitada para explorar, coletar recursos, fabricar ferramentas e criar estruturas. Os jogadores podem enfrentar monstros, explorar cavernas, construir cidades inteiras ou simplesmente expressar sua criatividade em um mundo gerado proceduralmente. Seu impacto cultural o tornou um dos jogos mais vendidos da história.', '2014-09-05', 'Sobrevivência', 'Xbox One', 9.8, 8, 9),
('TheWitcher3TrailerID', 50.00, 'The Witcher 3: Wild Hunt', 'CD Projekt Red', 'The Witcher 3: Wild Hunt acompanha Geralt de Rívia em uma busca por sua filha adotiva enquanto enfrenta monstros, guerras e forças sobrenaturais. O jogo apresenta um enorme mundo aberto repleto de missões detalhadas, escolhas com consequências significativas e personagens memoráveis. É amplamente considerado um dos maiores RPGs já criados.', '2015-05-19', 'RPG', 'Xbox One', 9.9, 4, 9),
('CupheadTrailerID', 25.00, 'Cuphead', 'Studio MDHR', 'Cuphead é um jogo de ação inspirado nos desenhos animados da década de 1930, apresentando animações desenhadas à mão e trilha sonora baseada em jazz. O jogo é famoso por seus chefes desafiadores, combate preciso e visual único, exigindo reflexos rápidos e domínio das mecânicas para avançar.', '2017-09-29', 'Ação', 'Xbox One', 9.3, 1, 9),
('SunsetOverdriveTrailerID', 25.00, 'Sunset Overdrive', 'Insomniac Games', 'Sunset Overdrive é um jogo de ação em mundo aberto ambientado em uma cidade dominada por mutantes criados por uma bebida energética contaminada. O jogador utiliza armas extravagantes, movimentação acrobática e trilhos espalhados pelo cenário para realizar combates rápidos e caóticos. Seu humor exagerado e gameplay criativo o tornaram um dos exclusivos mais marcantes do Xbox One.', '2014-10-28', 'Ação', 'Xbox One', 8.8, 1, 9),
/*XBOX SERIES S*/
('HaloInfiniteTrailerID', 70.00, 'Halo Infinite', '343 Industries', 'Halo Infinite acompanha Master Chief em uma nova batalha contra os Banished em um gigantesco anel Halo parcialmente destruído. O jogo introduz áreas semiabertas para exploração, equipamentos inéditos como o gancho de agarrar e uma campanha focada em recuperar a esperança da humanidade. Além da história principal, o multiplayer gratuito oferece modos competitivos e cooperativos que expandem a experiência clássica da franquia.', '2021-12-08', 'Ação', 'Xbox Series S', 8.8, 1, 10),
('ForzaHorizon5TrailerID', 60.00, 'Forza Horizon 5', 'Playground Games', 'Forza Horizon 5 leva os jogadores para uma enorme representação do México, oferecendo desertos, florestas tropicais, cidades históricas, praias e vulcões. O jogo apresenta centenas de carros licenciados, clima dinâmico, eventos variados e um vasto mundo aberto repleto de atividades. Seus gráficos impressionantes e dirigibilidade refinada o colocam entre os melhores jogos de corrida da atualidade.', '2021-11-09', 'Corrida', 'Xbox Series S', 9.6, 6, 10),
('StarfieldTrailerID', 70.00, 'Starfield', 'Bethesda Game Studios', 'Starfield é um RPG de exploração espacial ambientado em um futuro onde a humanidade colonizou diversos sistemas estelares. O jogador cria seu próprio personagem, pilota naves, explora planetas, participa de conflitos políticos e descobre mistérios espalhados pela galáxia. O jogo oferece enorme liberdade de escolha, personalização detalhada e uma grande quantidade de missões e conteúdos opcionais.', '2023-09-06', 'RPG', 'Xbox Series S', 8.7, 4, 10),
('GroundedTrailerID', 40.00, 'Grounded', 'Obsidian Entertainment', 'Grounded é um jogo de sobrevivência onde os protagonistas são misteriosamente reduzidos ao tamanho de insetos e precisam sobreviver em um quintal transformado em um ambiente gigantesco e perigoso. O jogador coleta recursos, constrói bases, fabrica equipamentos e enfrenta criaturas como formigas, aranhas e besouros enquanto tenta descobrir a causa do fenômeno.', '2022-09-27', 'Sobrevivência', 'Xbox Series S', 8.9, 8, 10),
('Psychonauts2TrailerID', 60.00, 'Psychonauts 2', 'Double Fine Productions', 'Psychonauts 2 acompanha Razputin Aquato em uma aventura dentro da mente de diferentes personagens, explorando cenários criativos que representam emoções, memórias e traumas. O jogo mistura plataforma, combate e resolução de puzzles enquanto desenvolve uma narrativa divertida e surpreendentemente profunda sobre saúde mental e crescimento pessoal.', '2021-08-25', 'Aventura', 'Xbox Series S', 9.3, 2, 10),
('HiFiRushTrailerID', 50.00, 'Hi-Fi Rush', 'Tango Gameworks', 'Hi-Fi Rush é um jogo de ação onde praticamente tudo acontece no ritmo da música. O jogador controla Chai, um jovem que acaba envolvido em uma conspiração corporativa e utiliza ataques sincronizados com a trilha sonora para derrotar inimigos. O visual estilizado, a jogabilidade criativa e o humor leve fizeram dele uma das maiores surpresas dos últimos anos.', '2023-01-25', 'Ação', 'Xbox Series S', 9.2, 1, 10),
('Hellblade2TrailerID', 70.00, 'Senuas Saga: Hellblade II', 'Ninja Theory', 'Senuas Saga: Hellblade II continua a jornada da guerreira Senua em uma aventura sombria inspirada na mitologia nórdica. O jogo combina narrativa cinematográfica, exploração e combates brutais enquanto retrata de forma intensa os conflitos psicológicos da protagonista. Seus gráficos extremamente avançados e sua atmosfera imersiva fazem dele uma das produções mais impressionantes da geração atual.', '2024-05-21', 'Aventura', 'Xbox Series S', 9.0, 2, 10),
/*PSP*/
('vYYZm2-HKvI',250.00,'Yu-Gi-Oh!_5Ds_Tag_Force_5',				'Konami',               'Yu-Gi-Oh! 5Ds Tag Force 5 (2010, PSP) mergulha no universo da terceira temporada do anime, onde o jogador, como o "Hat Guy", explora Neo Domino City e Satellite. A trama foca no WRGP e no confronto contra os Três Imperadores de Iliaster, que viajam do futuro para destruir a cidade com robôs androides. Junto aos Signers (Yusei, Jack, Crow, entre outros), você luta para impedir essa ameaça, com a narrativa mudando conforme o parceiro de duelo escolhido para o torneio final.', 																		'2010-09-16','Estrategia','PSP', 8.0 ,7 ,11),
('GodOfWarChainsOfOlympusTrailerID', 20.00, 'God of War: Chains of Olympus', 'Ready at Dawn', 'God of War: Chains of Olympus é uma aventura de ação que serve como prelúdio para a saga original de Kratos. O jogador enfrenta criaturas mitológicas, resolve puzzles e participa de batalhas épicas enquanto o protagonista serve aos deuses do Olimpo. Mesmo lançado para um portátil, o jogo impressionou pela qualidade gráfica, escala dos confrontos e fidelidade à franquia principal.', '2008-03-04', 'Ação', 'PSP', 9.1, 1, 11),
('GodOfWarGhostOfSpartaTrailerID', 25.00, 'God of War: Ghost of Sparta', 'Ready at Dawn', 'God of War: Ghost of Sparta aprofunda o passado de Kratos ao revelar detalhes sobre sua família e sua transformação no Fantasma de Esparta. O jogo apresenta combates ainda mais intensos, novas armas, chefes gigantescos e uma narrativa emocional que complementa os eventos da trilogia principal.', '2010-11-02', 'Ação', 'PSP', 9.3, 1, 11),
('CrisisCoreFF7TrailerID', 25.00, 'Crisis Core: Final Fantasy VII', 'Square Enix', 'Crisis Core: Final Fantasy VII acompanha Zack Fair em sua trajetória dentro da SOLDIER e mostra eventos que antecedem a história de Final Fantasy VII. O jogo mistura combate em tempo real, evolução de personagens e uma narrativa emocionante que explora personagens importantes como Cloud, Sephiroth e Aerith. É considerado uma das histórias mais marcantes da franquia Final Fantasy.', '2007-09-13', 'RPG', 'PSP', 9.4, 4, 11),
('MonsterHunterFreedomUniteTrailerID', 20.00, 'Monster Hunter Freedom Unite', 'Capcom', 'Monster Hunter Freedom Unite coloca os jogadores na pele de caçadores encarregados de enfrentar criaturas gigantescas em missões desafiadoras. O jogo oferece dezenas de armas diferentes, equipamentos criáveis a partir de materiais coletados e uma enorme quantidade de conteúdo. Sua experiência cooperativa ajudou a popularizar a série mundialmente.', '2008-03-27', 'RPG', 'PSP', 9.0, 4, 11),
('GTALibertyCityStoriesTrailerID', 20.00, 'Grand Theft Auto: Liberty City Stories', 'Rockstar Leeds', 'Grand Theft Auto: Liberty City Stories leva os jogadores de volta à famosa Liberty City em uma história focada na ascensão de Toni Cipriani dentro do crime organizado. O jogo oferece missões variadas, exploração livre da cidade, veículos diversos e toda a liberdade característica da franquia GTA.', '2005-10-24', 'Ação', 'PSP', 8.8, 1, 11),
('GTAViceCityStoriesTrailerID', 20.00, 'Grand Theft Auto: Vice City Stories', 'Rockstar Leeds', 'Grand Theft Auto: Vice City Stories explora eventos anteriores aos de GTA Vice City através da história de Victor Vance. O jogador participa de missões criminosas, administra negócios ilegais e explora uma cidade inspirada em Miami durante os anos 80. O jogo expande significativamente o conteúdo disponível em relação ao seu antecessor portátil.', '2006-10-31', 'Ação', 'PSP', 9.0, 1, 11),
('MetalGearPeaceWalkerTrailerID', 25.00, 'Metal Gear Solid: Peace Walker', 'Kojima Productions', 'Metal Gear Solid: Peace Walker acompanha Big Boss em uma operação militar na América Central durante a Guerra Fria. O jogo combina furtividade, gerenciamento de recursos, recrutamento de soldados e missões cooperativas. Sua narrativa possui grande importância para a cronologia da série Metal Gear.', '2010-04-29', 'Ação', 'PSP', 9.2, 1, 11),
('DaxterTrailerID', 15.00, 'Daxter', 'Ready at Dawn', 'Daxter é um jogo de plataforma estrelado pelo divertido companheiro da série Jak and Daxter. A aventura acontece durante os eventos entre Jak II e Jak 3, apresentando fases variadas, humor constante e mecânicas de plataforma acessíveis. O título é frequentemente considerado um dos melhores jogos já lançados para PSP.', '2006-03-14', 'Aventura', 'PSP', 8.7, 2, 11),
('TekkenDarkResurrectionTrailerID', 20.00, 'Tekken: Dark Resurrection', 'Bandai Namco', 'Tekken: Dark Resurrection é uma versão aprimorada de Tekken 5 que traz dezenas de lutadores, novos cenários e ajustes de balanceamento. O jogo oferece modos para um jogador e multiplayer, mantendo a profundidade técnica e a competitividade que tornaram a franquia Tekken uma das maiores referências do gênero luta.', '2005-07-06', 'Luta', 'PSP', 9.0, 3, 11);




SELECT * FROM USUARIO;
SELECT * FROM JOGOS;
select * from carrinho;